# Generated by Django 5.0.7 on 2024-08-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='STUDENT',
        ),
    ]
