# Generated by Django 5.0.7 on 2024-08-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_rename_item_college'),
        ('student', '0002_rename_item_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.college'),
            preserve_default=False,
        ),
    ]
